---
dist: xenial
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=betacloud/horizon
  matrix:
    - VERSION=rocky-2019.3.0
    - VERSION=rocky-2019.4.0

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#betacloud"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
