---
dist: xenial
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=betacloud/horizon
  matrix:
    - VERSION=rocky-2019.3.0
    - VERSION=rocky-2019.4.0

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  irc:
    channels:
      - "irc.freenode.org#betacloud"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
