---
name: Build docker image

"on":
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Dockerfile
      - files/**

jobs:
  default:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        brand:
          - plusserver
          - scs

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          build-args: BRAND=${{ matrix.brand }}
          push: false
