---
name: Push docker image

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/push-docker-image.yml
      - Dockerfile
      - files/**

jobs:

  default:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        brand:
          - plusserver
          - scs

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          build-args: BRAND=${{ matrix.brand }}
          push: true
          tags: quay.io/sovereigncloudstack/horizon:ussuri-${{ matrix.brand }}
